// <auto-generated />
namespace EximBd960.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class modelsalmotdone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelsalmotdone));
        
        string IMigrationMetadata.Id
        {
            get { return "202003050600052_models almot done"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
